Avoid "unused function parameter" compiler warning
protobuf-c/protobuf-c pull request #453
Opened 2021-01-19 14:56 UTC by wolframroesler

Use `_attribute__((__unused__))` for the `allocator_data` parameter of functions `system_alloc` and `system_free`. This allows us to integrate the file into build environments in which the "unused function parameter" warning is active. For example, with gcc 10 this avoids the following warnings:

```
protobuf-c.c: In function ‘system_alloc’:
protobuf-c.c:149:44: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
  149 | system_alloc(void *__attribute__((unused)) allocator_data, size_t size)
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
protobuf-c.c: In function ‘system_free’:
protobuf-c.c:155:43: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
  155 | system_free(void *__attribute__((unused)) allocator_data, void *data)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
```

2021-02-05 17:09 UTC, lipnitsk commented
Could you use a more portable solution without attributes, for example,
would `(void)allocator_data;` work?

On Tue, Jan 19, 2021, 06:57 Wolfram Rösler <notifications@github.com> wrote:

> Use _attribute__((__unused__)) for the allocator_data parameter of
> functions system_alloc and system_free. This allows us to integrate the
> file into build environments in which the "unused function parameter"
> warning is active. For example, with gcc 10 this avoids the following
> warnings:
>
> protobuf-c.c: In function ‘system_alloc’:
>
> protobuf-c.c:149:44: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
>
>   149 | system_alloc(void *__attribute__((unused)) allocator_data, size_t size)
>
>       |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
>
> protobuf-c.c: In function ‘system_free’:
>
> protobuf-c.c:155:43: error: unused parameter ‘allocator_data’ [-Werror=unused-parameter]
>
>   155 | system_free(void *__attribute__((unused)) allocator_data, void *data)
>
>       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
>
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/protobuf-c/protobuf-c/pull/453
> Commit Summary
>
>    - Avoid "unused function parameter" compiler warning
>
> File Changes
>
>    - *M* protobuf-c/protobuf-c.c
>    <https://github.com/protobuf-c/protobuf-c/pull/453/files#diff-ec49d7823ada420c8af76baa77438e5304515c031911fe8faefce469e136c033>
>    (4)
>
> Patch Links:
>
>    - https://github.com/protobuf-c/protobuf-c/pull/453.patch
>    - https://github.com/protobuf-c/protobuf-c/pull/453.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/protobuf-c/protobuf-c/pull/453>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADLEAKSTTAHCB57MNDTIALS2WMUBANCNFSM4WI4UCEQ>
> .
>

2021-02-09 13:30 UTC, wolframroesler commented
Casting to void is likely to have the same effect as the `__attribute__((__unused__))`. Changed it as requested.

2021-02-19 02:25 UTC, edmonds requested changes
Please squash the changes into a single commit.

2021-02-19 02:34 UTC, lipnitsk commented
@edmonds @wolframroesler I went ahead and squashed it.

2021-02-19 02:35 UTC, edmonds approved these changes

2021-02-19 02:36 UTC, merged